// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NundoTv_WebAPI.Data;

#nullable disable

namespace NundoTv_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526114339_InitialIptv")]
    partial class InitialIptv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BlockRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<List<string>>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("BlockedChannels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlockedKeywords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keyword = "xxx"
                        },
                        new
                        {
                            Id = 2,
                            Keyword = "porn"
                        },
                        new
                        {
                            Id = 3,
                            Keyword = "adult"
                        },
                        new
                        {
                            Id = 4,
                            Keyword = "sex"
                        },
                        new
                        {
                            Id = 5,
                            Keyword = "18+"
                        },
                        new
                        {
                            Id = 6,
                            Keyword = "nsfw"
                        },
                        new
                        {
                            Id = 7,
                            Keyword = "onlyfans"
                        },
                        new
                        {
                            Id = 8,
                            Keyword = "hentai"
                        },
                        new
                        {
                            Id = 9,
                            Keyword = "casino"
                        },
                        new
                        {
                            Id = 10,
                            Keyword = "gambling"
                        });
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<List<string>>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WatchDurationSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelemetryEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
