// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NundoTv_WebAPI.Data;

#nullable disable

namespace NundoTv_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607103551_AddConsentFields")]
    partial class AddConsentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BlockRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("BlockedChannels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannelLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockedChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Feed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("InUse")
                        .HasColumnType("boolean");

                    b.Property<string>("IptvChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockedChannelId");

                    b.ToTable("BlockedChannelLogos");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlockedKeywords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keyword = "xxx"
                        },
                        new
                        {
                            Id = 2,
                            Keyword = "porn"
                        },
                        new
                        {
                            Id = 3,
                            Keyword = "adult"
                        },
                        new
                        {
                            Id = 4,
                            Keyword = "sex"
                        },
                        new
                        {
                            Id = 5,
                            Keyword = "18+"
                        },
                        new
                        {
                            Id = 6,
                            Keyword = "nsfw"
                        },
                        new
                        {
                            Id = 7,
                            Keyword = "onlyfans"
                        },
                        new
                        {
                            Id = 8,
                            Keyword = "hentai"
                        },
                        new
                        {
                            Id = 9,
                            Keyword = "casino"
                        },
                        new
                        {
                            Id = 10,
                            Keyword = "gambling"
                        });
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.ChannelLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Feed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("InUse")
                        .HasColumnType("boolean");

                    b.Property<string>("IptvChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelLogos");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.IMerlChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImerlChannels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interest");

                    b.HasData(
                        new
                        {
                            Id = new Guid("52a6dd79-bb0a-4224-a8c8-83bc09f1281e"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("05d9b552-639a-4d78-a261-d3aa6675a616"),
                            Name = "News"
                        },
                        new
                        {
                            Id = new Guid("e2b9ea42-9240-45cf-a04a-012f770f4326"),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("94515ebf-d900-4114-b06e-449147b4cf66"),
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = new Guid("377b83c0-d307-4750-bdc7-4460fd7998da"),
                            Name = "Kids"
                        },
                        new
                        {
                            Id = new Guid("684192c0-3b2f-49a3-a893-6b80df12e45e"),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("50846e37-f81f-4b54-b3fa-9c99bf734657"),
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("dd4070c2-aa01-48ca-9e1e-ca8b3cf950d5"),
                            Name = "Reality Show"
                        },
                        new
                        {
                            Id = new Guid("556cca01-d02f-488d-88a3-8fd4d09f767f"),
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = new Guid("863dd752-2494-4b8d-a585-76553b2d84ba"),
                            Name = "Discoveries"
                        },
                        new
                        {
                            Id = new Guid("e198424a-a924-4ac6-b420-7eba685908d6"),
                            Name = "Anime"
                        },
                        new
                        {
                            Id = new Guid("5507972f-9496-4030-963e-6bd4a05fece6"),
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("cbbb7dd5-e4bc-4817-ad64-00a28041ecaa"),
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WatchDurationSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasConsentedToAds")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasConsentedToDataSharing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremiumAdFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterest");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannelLogo", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.BlockedChannel", "BlockedChannel")
                        .WithMany()
                        .HasForeignKey("BlockedChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedChannel");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.ChannelLogo", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.UserInterest", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NundoTv_WebAPI.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.User", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
