// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NundoTv_WebAPI.Data;

#nullable disable

namespace NundoTv_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BlockRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("BlockedChannels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannelLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockedChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Feed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("InUse")
                        .HasColumnType("boolean");

                    b.Property<string>("IptvChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockedChannelId");

                    b.ToTable("BlockedChannelLogos");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlockedKeywords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Keyword = "xxx"
                        },
                        new
                        {
                            Id = 2,
                            Keyword = "porn"
                        },
                        new
                        {
                            Id = 3,
                            Keyword = "adult"
                        },
                        new
                        {
                            Id = 4,
                            Keyword = "sex"
                        },
                        new
                        {
                            Id = 5,
                            Keyword = "18+"
                        },
                        new
                        {
                            Id = 6,
                            Keyword = "nsfw"
                        },
                        new
                        {
                            Id = 7,
                            Keyword = "onlyfans"
                        },
                        new
                        {
                            Id = 8,
                            Keyword = "hentai"
                        },
                        new
                        {
                            Id = 9,
                            Keyword = "casino"
                        },
                        new
                        {
                            Id = 10,
                            Keyword = "gambling"
                        });
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Closed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IptvId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Launched")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Owners")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReplacedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("IptvId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.ChannelLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("Feed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("InUse")
                        .HasColumnType("boolean");

                    b.Property<string>("IptvChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelLogos");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.IMerlChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImerlChannels");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bdd18f8-0af2-41fb-ac78-f22ea52bc3db"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("61107eb1-86d6-4d6f-93e9-6888cc335a2a"),
                            Name = "News"
                        },
                        new
                        {
                            Id = new Guid("2fb507af-70f1-492a-a7e3-b0335c27ebe9"),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("8d27048a-773c-4530-a298-b1a7c43df201"),
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = new Guid("d0ba9a2f-bad5-495f-a7ad-fd33fbe9296f"),
                            Name = "Kids"
                        },
                        new
                        {
                            Id = new Guid("8fe0abf8-08a2-4ec0-b810-b26b5c41f1e1"),
                            Name = "Movies"
                        },
                        new
                        {
                            Id = new Guid("3f4e3aa7-6492-4e33-a4b5-0147e3c3acbb"),
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("c8fdbae6-3886-4f4f-b01e-ed2325591b84"),
                            Name = "Reality Show"
                        },
                        new
                        {
                            Id = new Guid("a466bfe4-954f-442c-8abd-40baaa067520"),
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = new Guid("485cf338-8ee5-4038-a629-651311c4d5f4"),
                            Name = "Discoveries"
                        },
                        new
                        {
                            Id = new Guid("668d01f4-825c-4f63-9066-e36c779bae5b"),
                            Name = "Anime"
                        },
                        new
                        {
                            Id = new Guid("5e9776f1-1668-4de1-bbea-adc29b5795db"),
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("ac45bc0a-c4ea-435d-b61f-c50cb8901c1f"),
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.TelemetryEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WatchDurationSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasConsentedToAds")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasConsentedToDataSharing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremiumAdFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClerkId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.BlockedChannelLogo", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.BlockedChannel", "BlockedChannel")
                        .WithMany()
                        .HasForeignKey("BlockedChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedChannel");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.ChannelLogo", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.UserInterest", b =>
                {
                    b.HasOne("NundoTv_WebAPI.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NundoTv_WebAPI.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("NundoTv_WebAPI.Models.User", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
